---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-payment-pvc
  namespace: mobility
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-payment
  namespace: mobility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-payment
  template:
    metadata:
      labels:
        app: mongo-payment
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-payment-storage
              mountPath: /data/db
      volumes:
        - name: mongo-payment-storage
          persistentVolumeClaim:
            claimName: mongo-payment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-payment
  namespace: mobility
spec:
  selector:
    app: mongo-payment
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: mobility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/kektri/cloudcomputing/payment-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-payment:27017"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: mobility
spec:
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 8000
