---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
  namespace: mobility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-service
          image: ghcr.io/kektri/cloudcomputing/tracking-service:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "64Mi"
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: mobility
spec:
  selector:
    app: tracking-service
  ports:
    - port: 80
      targetPort: 8000
